spring:
  jpa:
    api:
      open-in-view: false
      generate-ddl: false
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate.ddl-auto: none
      show-sql: false
      properties:
        hibernate:
          storage_engine: innodb
          hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          default_batch_fetch_size: ${DB_FETCH_CHUNKSIZE:250}
          format_sql: true
          highlight_sql: true
          use_sql_comments: true
          connection.provider_disables_autocommit: true
          connection.provider_disables_autocommit_false: false
          globally_quoted_identifiers: true
          order_inserts: true
          order_updates: true
          implicit_naming_strategy: com.tech.n.ai.domain.aurora.utils.JpaImplicitNamingStrategyCustom
          physical_naming_strategy: com.tech.n.ai.domain.aurora.utils.JpaPhysicalNamingStrategyCustom
          jdbc:
            batch_size: ${DB_BATCH_SIZE:50}
            time_zone: ${TZ:Asia/Seoul}

  datasource:
    api:
      writer:
        hikari:
          driver-class-name: software.aws.rds.jdbc.mysql.Driver
          connection-timeout: 5000
          validation-timeout: 5000
          max-lifetime: 28795000
          idle-timeout: 300000
          minimum-idle: 5
          maximum-pool-size: 20
          auto-commit: false
          transaction-isolation: TRANSACTION_READ_UNCOMMITTED
          data-source-properties:
            connectTimeout: 5000
            socketTimeout: 60000
            useUnicode: true
            characterEncoding: utf-8
            rewriteBatchedStatements: true
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
            wrapperPlugins: readWriteSplitting,failover,efm
            failoverMode: reader-or-writer
      reader:
        hikari:
          driver-class-name: software.aws.rds.jdbc.mysql.Driver
          connection-timeout: 5000
          validation-timeout: 5000
          max-lifetime: 28795000
          idle-timeout: 300000
          minimum-idle: 5
          maximum-pool-size: 20
          auto-commit: false
          transaction-isolation: TRANSACTION_READ_UNCOMMITTED
          data-source-properties:
            connectTimeout: 5000
            socketTimeout: 60000
            useUnicode: true
            characterEncoding: utf-8
            rewriteBatchedStatements: true
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
            wrapperPlugins: readWriteSplitting,failover,efm
            failoverMode: reader-or-writer

management:
  health:
    db:
      enabled: false

logging:
  level:
    org.hibernate.type: warn
    org.hibernate.sql: warn
    org.hibernate.type.descriptor.sql: warn
    org.hibernate.orm: warn

mybatis:
  config-location: "classpath:mapper-config.xml"

---
spring:
  config.activate.on-profile: local

  datasource:
    api:
      writer:
        hikari:
          data-source-properties:
            wrapperPlugins: ""
            useConnectionPlugins: false
      reader:
        hikari:
          data-source-properties:
            wrapperPlugins: ""
            useConnectionPlugins: false
    writer:
      url: jdbc:mysql://localhost:${module.mysql.port}/${module.aurora.schema}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: admin
      password: admin1234
    reader:
      url: jdbc:mysql://localhost:${module.mysql.port}/${module.aurora.schema}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: admin
      password: admin1234

---
spring:
  config.activate.on-profile: dev

  datasource:
    writer:
      url: jdbc:mysql://tech-n-ai-aurora-cluster-instance-1.c8hcnykzcnr8.ap-northeast-2.rds.amazonaws.com:3306/${module.aurora.schema}?${AURORA_OPTIONS:useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
      username: admin
      password: admin1234
    reader:
      url: jdbc:mysql://tech-n-ai-aurora-cluster-instance-1.c8hcnykzcnr8.ap-northeast-2.rds.amazonaws.com:3306/${module.aurora.schema}?${AURORA_OPTIONS:useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
      username: admin
      password: admin1234

---
spring:
  config.activate.on-profile: beta

  datasource:
    writer:
      url: jdbc:mysql://tech-n-ai-aurora-cluster-instance-1.c8hcnykzcnr8.ap-northeast-2.rds.amazonaws.com:3306/${module.aurora.schema}?${AURORA_OPTIONS:useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
      username: admin
      password: admin1234
    reader:
      url: jdbc:mysql://tech-n-ai-aurora-cluster-instance-1.c8hcnykzcnr8.ap-northeast-2.rds.amazonaws.com:3306/${module.aurora.schema}?${AURORA_OPTIONS:useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
      username: admin
      password: admin1234

---
spring:
  config.activate.on-profile: prod

  datasource:
    writer:
      url: jdbc:mysql://tech-n-ai-aurora-cluster-instance-1.c8hcnykzcnr8.ap-northeast-2.rds.amazonaws.com:3306/${module.aurora.schema}?${AURORA_OPTIONS:useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
      username: admin
      password: admin1234
    reader:
      url: jdbc:mysql://tech-n-ai-aurora-cluster-instance-1.c8hcnykzcnr8.ap-northeast-2.rds.amazonaws.com:3306/${module.aurora.schema}?${AURORA_OPTIONS:useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
      username: admin
      password: admin1234


logging:
  level:
    org.hibernate.type: error
    org.hibernate.sql: error