group = 'com.tech.n.ai.api'
version = '0.0.1-SNAPSHOT'
description = 'api-auth'

bootJar.enabled = true
jar.enabled = false

apply from: "${rootDir.absolutePath}/docs.gradle"
apply from: "${rootDir.absolutePath}/jpa.gradle"

dependencies {
	implementation project(':datasource-aurora')
	implementation project(':datasource-mongodb')
	implementation project(':common-core')
	implementation project(':common-security')
	implementation project(':common-exception')
	implementation project(':client-feign')
	implementation project(':client-mail')
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

	testImplementation 'org.springframework.security:spring-security-test'
}

task prepareKotlinBuildScriptModel {

}
