group = 'com.tech.n.ai.api'
version = '0.0.1-SNAPSHOT'
description = 'api-emerging-tech'

bootJar.enabled = true
jar.enabled = false

apply from: "${rootDir.absolutePath}/docs.gradle"

dependencies {
	// langchain4j (임베딩 생성용)
	implementation 'dev.langchain4j:langchain4j'
	implementation 'dev.langchain4j:langchain4j-open-ai'

	implementation project(':common-core')
	implementation project(':common-exception')
	implementation project(':datasource-mongodb')
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

task prepareKotlinBuildScriptModel {

}
