spring:
  config:
    activate:
      on-profile: beta
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowCredentials: true
                allowedOriginPatterns:
                  - "https://beta.example.com"
                  - "https://example.com"
                allowedHeaders: "*"
                allowedMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD]
                maxAge: 3600
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

gateway:
  routes:
    auth:
      uri: http://api-auth-service:8080
    bookmark:
      uri: http://api-bookmark-service:8080
    chatbot:
      uri: http://api-chatbot-service:8080
    agent:
      uri: http://api-agent-service:8080
    emerging-tech:
      uri: http://api-emerging-tech-service:8080

logging:
  level:
    com.tech.n.ai.api.gateway: WARN
    ACCESS_LOG: INFO
