server:
  port: 8086

spring:
  application:
    name: agent-api
  profiles:
    include:
      - common-core
      - kafka
      - api-domain
      - agent-api
      - mongodb-domain
      - feign-github
      - feign-internal
      - slack
      - scraper
      - rss

module:
  mysql:
    port: ${MYSQL_PORT:3310}
  aurora:
    schema: ${AURORA_SCHEMA:chatbot}
